### ISSUE TITLE
more than one template per language

### ISSUE THREAD

**Issue by martinlindelof** [nvimdev/template.nvim#34]
I've made one cobol template, works.
I've made 3 C templates, depending on what libs I'm gonna use. But the lua plugin only finds _only_ the latest added c template when running :Template 

Is it possible to load multiple templates for a single language? Am I doing something wrong in the setup.

**Comment by glepnir** [comment]
it should return all template for this language.  maybe a bug ? I will test it later.

**Comment by martinlindelof** [comment]
Only hint I noticed is whatever template c file I create latest, is the only template showing up.
I remember now, compiled new nvim from source this morning!
Problem might be something in neovim github repo.
So if you do some testing later today, that's a hint. 
I'm actually 99% sure it worked with multiple template files for C last week, or two weeks ago.

**Comment by martinlindelof** [comment]
nvim --version                                                                                  
NVIM v0.10.0-dev-18+gb6d5047d4
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

:checkhealth 
Looks fine!

**Comment by glepnir** [comment]
you mean this commit works fine right ？

**Comment by martinlindelof** [comment]
No, earlier builds worked. This one from yesterday is when I noticed it broke.
I only get one template with :Template command.
BUT if I manually write out the template file without tab completion the plugin can load the template file.

**Comment by glepnir** [comment]
i think it had fixed .. did you update ?
