### ISSUE TITLE
Not recognizing .tex files

### ISSUE THREAD

**Issue by LuisA92** [nvimdev/template.nvim#37]
I get the following errors when I start neovim: 

```
[Template.nvim] Could not find the filetype of template file path/to/template/.DS_Store
[Template.nvim] Could not find the filetype of template file path/to/template/tex_template.tex
```

I do not get the error if I change `.tex` to `.latex`. 

Can I ignore the `.DS_Store` filetype?

**Comment by glepnir** [comment]
because for text file neovim need content to detect what filetype it is . try use `*.tpl` and first line of this tpl file is `;; latex`.

**Comment by LuisA92** [comment]
> because for text file neovim need content to detect what filetype it is . try use `*.tpl` and first line of this tpl file is `;; latex`.

This worked, thank you.

**Comment by glepnir** [comment]
closed
