### ISSUE TITLE
Define custom items in template grammar

### ISSUE THREAD

**Issue by nkakouros** [nvimdev/template.nvim#38]
I would like to define a pattern, e.g. 

`{{_tomorrow_}}`

that would do what 

`{{_lua:os.execute('date --date="next day" +%Y-%m-%d')_}}` 

would do. The reason is that I use the tomorrow date in several places in my templates and it is hard to maintain it by replicating the lua snippet everywhere.

**Comment by nkakouros** [comment]
Thank you adding this by default in your plugin. 

But given that users will have a lot of different types of such patterns, would you consider providing a way to the user to extend the expr table?

**Comment by glepnir** [comment]
provide a custom expression interface will make sense.
