### ISSUE TITLE
Tab completion eats up new file name

### ISSUE THREAD

**Issue by nkakouros** [nvimdev/template.nvim#40]
If I have a template names `mytemplate.md` and then try to load it using:

```
:Template myfile<TAB>
```

what happens is that `myfile` gets replaced with `mytemplate`. Notice the missing space after `myfile` and before `<TAB>`. I don't know if this is a bug with neovim or this plugin.

**Comment by glepnir** [comment]
you need space after my file.

**Comment by glepnir** [comment]
hmm does myfile exits ? if exist and is current buffer why you input it. `Template test.md <TAB>` this test.md is not exist then template will create it and open it
