### ISSUE TITLE
Multiple lua patterns on the same line trigger error

### ISSUE THREAD

**Issue by nkakouros** [nvimdev/template.nvim#41]
If in a template I have the following:

```
# {{_lua:'123'_}} - {{_lua:'abc'_}}
```

Then I get an error:

```
Error executing vim.schedule lua callback: ...te/pack/packer/start/template.nvim/lua/template/init.lua:72: attempt to call a nil value
stack traceback:
        ...te/pack/packer/start/template.nvim/lua/template/init.lua:72: in function <...te/pack/packer/start/template.nvim/lua/template/init.lua:71>
        ...te/pack/packer/start/template.nvim/lua/template/init.lua:161: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

BTW, thank for creating this plugin, I was looking for an nvim alternative to `vim-template`.

**Comment by glepnir** [comment]
hmm I never  hear that plugin .. this plugin idea from mattn template plugin

**Comment by nkakouros** [comment]
🚀

**Comment by nkakouros** [comment]
It still does not work, I get the same error.  In the following lines:

https://github.com/nvimdev/template.nvim/blob/85c514bb7f7457a50598a702512e979e8adf098f/lua/template/init.lua#L94-L114

it seems to me that the same expr is never checked twice on the same line. Also, the `{{_lua:.*_}}` expression will match the lua snippets wrong. E.g. if the line is:

```
{{_lua:'111'_}} - {{_lua:'222'_}}
```

the `find` function will return:

```
'111'_}} - {{_lua:'222'
```

which is wrong.

**Comment by nkakouros** [comment]
Actually, changing the pattern from `{{_lua:(.*)_}}` to `{{_lua:(.-)_}}` seems to fix the issue.

**Comment by glepnir** [comment]
`{{_lua:'111'_}} - {{_lua:'222'_}}` this is not a valid expression . what you want get `111` ?

**Comment by nkakouros** [comment]
This is just a simple example of the `lua:` expression. It works in the plugin, I don't know if it is valid lua. You can put two valid lua expressions, whichever you like, and if they are on the same line there is an error triggered because the pattern matching happens in a greedy way, it ends at the end of the second lua expressions. But even if you fix that part (with `.-` instead of `.*`), it will still not work ok, as both lua expressions will be replaced with the result of the first expression, due to `gsub` replacing the `lua:` expression everywhere in the line.

**Comment by glepnir** [comment]
maybe I  need add some test for these expressions.  if you make it works fine. PR welcome. I will review it
